# Key Pair (login)

resource "aws_key_pair" "my-key" {
  key_name = "ec2-terraform-key"
  public_key = file("ec2-terraform-key.pub")
}

# VPC & Security Groups

resource "aws_default_vpc" "default" {
  tags = {
    Name = "Default VPC"
  }
}

resource "aws_security_group" "my_security_group" {
  name = "automate-sg"
  description = "This will add a TF generated by Security Group"
  vpc_id = aws_default_vpc.default.id

  tags = {
    Name = "automate-sg"
  }
}

# -------------------
# INGRESS RULES
# -------------------



# -------------------
# EGRESS RULES
# -------------------


# EC2 Instance
